language: objective-c
osx_image: xcode9
before_install:
 -  SIMULATOR_ID=$(xcrun instruments -s | grep -o "iPhone 6 \(.*\) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")
script:
  - echo $SIMULATOR_ID
  - open -b com.apple.iphonesimulator --args -CurrentDeviceUDID $SIMULATOR_ID
  - fastlane scan
